language: nodejs
nodejs:
- '8'
sudo: required
services:
- docker
branches:
  only:
  - master
before_install:
- nvm install node
- docker-compose -f docker-compose.yml -f docker-compose.test.yml build
script:
- npm install --prefix backend/
- npm run lint --prefix backend/
- docker-compose -f docker-compose.test.yml run test
- cd frontend && npm install && npm run build-prod
- cp src/public/index.html build/
- mv build/ ../backend/src/
before_deploy:
- cd ../backend
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: you-encrypted-token
  on: master
  app: you-app-123
